apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-lego
  # namespace: kube-lego
data:
  # modify this to specify your address
  lego.email: "simon@rueggs.ch"
  # configre letencrypt's production api
  #lego.url: "https://acme-v01.api.letsencrypt.org/directory"
  lego.url: "https://acme-staging.api.letsencrypt.org/directory"
